-- Supabase SQL pentru Bringo WhatsApp Database Edition
-- Rulează acest script în Supabase → SQL Editor → Run.

create table if not exists public.bringo_app_store (
  store_key text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.bringo_app_backups (
  id bigint generated by default as identity primary key,
  store_key text not null,
  reason text,
  data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists bringo_app_backups_store_created_idx
  on public.bringo_app_backups (store_key, created_at desc);

-- Recomandat: backend-ul folosește SERVICE_ROLE_KEY, nu cheia publică anon.
-- Nu pune SERVICE_ROLE_KEY în aplicația HTML sau în frontend.
